"""followers

Revision ID: 922df0ba2cfe
Revises: 090b913f3004
Create Date: 2019-01-18 20:27:42.481003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922df0ba2cfe'
down_revision = '090b913f3004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('playlistname', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'playlistname')
    # ### end Alembic commands ###
